### ISSUE TITLE
Can't ls a certain folder

### ISSUE THREAD

**Issue by manwe** [oxfs/oxfs#13]
Hi. I have an issue that I cannot read the contents of a certain folder. Others work without issues. The only difference in this folder is that it contains 1162 files and it's 19TB although I don't know if it's related with the issue. 

[2021-12-27 12:12:45,767][INFO][_internal.py -- _log():225][ * Running on http://127.0.0.1:10010/ (Press CTRL+C to quit)]
[2021-12-27 13:05:24,744][ERROR][fuse.py -- _wrapper():750][Uncaught exception from FUSE operation readdir, returning errno.EINVAL.]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fuse.py", line 734, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python3.9/dist-packages/fuse.py", line 960, in readdir
    for item in self.operations('readdir', self._decode_optional_path(path),
  File "/usr/local/lib/python3.9/dist-packages/fuse.py", line 1251, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/local/lib/python3.9/dist-packages/oxfs/oxfs.py", line 234, in readdir
    entries = self.sftp.listdir(path)
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 218, in listdir
    return [f.filename for f in self.listdir_attr(path)]
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 254, in listdir_attr
    filename = msg.get_text()
  File "/usr/local/lib/python3.9/dist-packages/paramiko/message.py", line 178, in get_text
    return u(self.get_string())
  File "/usr/local/lib/python3.9/dist-packages/paramiko/py3compat.py", line 161, in u
    return s.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 56: invalid continuation byte

Any thoughts about how I can debug this?

cheers

**Comment by RainMark** [comment]
> Hi. I have an issue that I cannot read the contents of a certain folder. Others work without issues. The only difference in this folder is that it contains 1162 files and it's 19TB although I don't know if it's related with the issue.
> 
> [2021-12-27 12:12:45,767][INFO][_internal.py -- _log():225][ * Running on http://127.0.0.1:10010/ (Press CTRL+C to quit)] [2021-12-27 13:05:24,744][ERROR][fuse.py -- _wrapper():750][Uncaught exception from FUSE operation readdir, returning errno.EINVAL.] Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/fuse.py", line 734, in _wrapper return func(*args, **kwargs) or 0 File "/usr/local/lib/python3.9/dist-packages/fuse.py", line 960, in readdir for item in self.operations('readdir', self._decode_optional_path(path), File "/usr/local/lib/python3.9/dist-packages/fuse.py", line 1251, in **call** ret = getattr(self, op)(path, *args) File "/usr/local/lib/python3.9/dist-packages/oxfs/oxfs.py", line 234, in readdir entries = self.sftp.listdir(path) File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 218, in listdir return [f.filename for f in self.listdir_attr(path)] File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 254, in listdir_attr filename = msg.get_text() File "/usr/local/lib/python3.9/dist-packages/paramiko/message.py", line 178, in get_text return u(self.get_string()) File "/usr/local/lib/python3.9/dist-packages/paramiko/py3compat.py", line 161, in u return s.decode(encoding) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 56: invalid continuation byte
> 
> Any thoughts about how I can debug this?
> 
> cheers

Looks a bit like this issue: https://github.com/paramiko/paramiko/issues/707

**Comment by RainMark** [comment]
@manwe your sftp server running on Windows？

**Comment by manwe** [comment]
No, it's a synology NAS. DSM 6.2
