### ISSUE TITLE
ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers' 

### ISSUE THREAD

**Issue by XushanLu** [oxfs/oxfs#14]
Hello, 

Tried to mount my remote dir to my home directory using oxfs but got this:

oxfs --host xsl@siku --remote-path /home/xsl/ --mount-point ./siku --cache-path .oxfs --logging /tmp/oxfs.log --daemon
  --auto-cache
Traceback (most recent call last):
  File "/Users/xsl/.venv/oxfs/bin/oxfs", line 5, in <module>
    from oxfs.oxfs import main
  File "/Users/xsl/.venv/oxfs/lib/python3.9/site-packages/oxfs/oxfs.py", line 19, in <module>
    from oxfs.apiserver import OxfsApi
  File "/Users/xsl/.venv/oxfs/lib/python3.9/site-packages/oxfs/apiserver.py", line 6, in <module>
    from flask_restx import Resource, Api, fields
  File "/Users/xsl/.venv/oxfs/lib/python3.9/site-packages/flask_restx/__init__.py", line 5, in <module>
    from .api import Api  # noqa
  File "/Users/xsl/.venv/oxfs/lib/python3.9/site-packages/flask_restx/api.py", line 19, in <module>
    from flask.helpers import _endpoint_from_view_func
ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers' (/Users/xsl/.venv/oxfs/lib/python3.9/site-packages/flask/helpers.py)

Any idea?

Thanks.

**Comment by RainMark** [comment]
Looks like same to the issue:  https://github.com/oxfs/oxfs/issues/9
